env:
  browser: true
  commonjs: true
  es6: true
extends: ['plugin:react/recommended','eslint:recommended']
parser: babel-eslint
parserOptions:
  allowImportExportEverywhere: false
  codeFrame: false
  ecmaFeatures:
    experimentalObjectRestSpread: true
    jsx: true
  sourceType: module
plugins:
  - react
  - flowtype
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - double
  semi:
    - error
    - always
  react/jsx-uses-vars:
    - error
  flowtype/define-flow-type:
    - error
  flowtype/use-flow-type:
    - error
