// flow-typed signature: 0b644a043394ebc4522a214a8fe3c072
// flow-typed version: <<STUB>>/opener_v^1.4.3/flow_v0.54.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'opener'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'opener' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'opener/opener' {
  declare module.exports: any;
}

// Filename aliases
declare module 'opener/opener.js' {
  declare module.exports: $Exports<'opener/opener'>;
}
