// flow-typed signature: 2895f00d134d3d0a0ea739038f02559c
// flow-typed version: <<STUB>>/@storybook/react/demo_vv3.x.x/flow_v0.72.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@storybook/react/demo'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@storybook/react/demo' {
  declare module.exports: any;
}
